-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Aug 03, 2024 at 07:49 AM
-- Server version: 10.11.8-MariaDB-cll-lve
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u496524825_global`
--

-- --------------------------------------------------------

--
-- Table structure for table `pro`
--

CREATE TABLE `pro` (
  `id` int(100) NOT NULL,
  `pro_name` varchar(200) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(256) NOT NULL,
  `slug` varchar(256) NOT NULL,
  `short_dec` varchar(256) NOT NULL,
  `title` varchar(200) NOT NULL,
  `dec` varchar(200) NOT NULL,
  `keyword` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `pro`
--

INSERT INTO `pro` (`id`, `pro_name`, `description`, `image`, `slug`, `short_dec`, `title`, `dec`, `keyword`) VALUES
(1, 'Gauze Swabs', '<p>Gauze swabs, also known as surgical sponges or dressings, are indispensable tools in medical settings, used for various purposes ranging from wound cleaning to absorbing blood and fluids during surgical procedures. These small pieces of woven fabric are typically made from cotton or a blend of cotton and synthetic materials, ensuring they are sterile and absorbent. Germany is well-known for its high-quality medical supplies industry, including reputable <a href=\"single-product.php?slug=Gauze-Swabs\"> Gauze Swab exporters in Germany <a> who adhere to stringent standards of production and sterilization.</p>\n<p>\nIn surgical procedures, gauze swabs play a crucial role in maintaining a sterile field by absorbing blood and other fluids, thus keeping the surgical site clean and visible to the surgeon. They are also used to apply antiseptic solutions or medications to wounds, aiding in the healing process and preventing infection.\n</p>\n<p>\nOutside of the operating room, gauze swabs are commonly used in first aid kits and medical facilities for wound care. They are gentle on the skin and provide a soft barrier between the wound and the outside environment, helping to protect it from further injury or contamination.\n</p>\n<p>\nGauze swabs come in various sizes and ply, with the number of layers determining their absorbency and thickness. They are often packaged in sterile packets to maintain their cleanliness and are disposable after single use, reducing the risk of cross-contamination and infection.     \n</p>\n ', 'img/product/1.jpg', 'Gauze-Swabs', 'Discover the cornerstone of surgical care with our Gauze Swabs. Engineered with precision and crafted from...', 'Gauze Swab Exporters In Germany Globalsurgicare Industries', ' Leading Gauze Swab exporters in Germany ,delivering high-quality medical supplies worldwide with exceptional service and competitive pricing in your area easy.', ' Gauze Swab exporters in Germany  , Gauze Swab Supplier in Nepal   , Gauze Swab exporters in UAE '),
(2, 'X-Ray Detectable Gauze Swabs', '<p> X-ray detectable gauze swabs are a specialized type of gauze used in medical settings, particularly in surgeries where imaging such as X-rays are employed. These <a href=\"single-product.php?slug=X-Ray-Detectable-Gauze-Swabs\">  X-Ray Detectable Gauze Swabs in Germany<a> are designed with a unique feature that makes them visible under X-ray, aiding in their detection if accidentally left inside a patient\'s body during a surgical procedure.    </p>  ', 'img/product/2.jpg', 'X-Ray-Detectable-Gauze-Swabs', 'Introducing our X-ray Detectable Gauze Swabs, a revolutionary solution for surgical precision and safety....', 'X-Ray Detectable Gauze Swabs in Germany || Globalsurgicare', 'X-Ray Detectable Gauze Swabs in Germany, designed to elevate surgical safety and efficiency. Crafted with precision, these gauze swabs feature a Radiopaque', ' X-Ray Detectable Gauze Swabs in Germany  , X-Ray Detectable Gauze Swabs in Nepal , X-Ray Detectable Gauze Swabs in Netherlands , X-Ray Detectable Gauze Swabs in Oman \"'),
(3, 'Abdominal Gauze Pad Laparotomy Sponge ', '<p>Abdominal gauze pads, also known as laparotomy sponges or lap sponges, are large, absorbent dressings used specifically in abdominal surgeries and procedures. These pads are made from sterile woven cotton or a blend of cotton and synthetic materials and are designed to handle the unique demands of abdominal surgeries.\n\nDuring a laparotomy, which is a surgical procedure involving a large incision into the abdominal cavity, laparotomy sponges play a crucial role in maintaining a clean and dry surgical field. They are placed strategically within the abdomen to absorb blood, fluids, and other debris, thereby enhancing visibility for the surgeon and preventing contamination of internal organs and tissues.\n\nThe use of <a href=\"single-product.php?slug=Abdominal-Gauze-Pad-Laparotomy-Sponge\"> Abdominal Gauze Pad Laparotomy in Melbourne </a> X-ray detectable gauze swabs helps surgeons and medical staff to accurately locate any remaining surgical sponges or dressings within the patient\'s body before closing the incision. This reduces the risk of postoperative complications, such as infection or tissue damage, associated with retained foreign objects.\n\nThese pads are available in various sizes to accommodate different surgical needs and may come with or without a radiopaque marker. They are usually packaged in sterile packs for single-use to prevent cross-contamination and reduce the risk of surgical site infections.\"\n </p>  ', 'img/product/3new.jpg', 'Abdominal-Gauze-Pad-Laparotomy-Sponge', 'Our Gauze Swabs are meticulously crafted to meet the stringent demands of surgical ...', 'Abdominal Gauze Pad Laparotomy in Melbourne | Globalsurgicl', 'Experience top-notch abdominal gauze pad laparotomy services in Melbourne, ensuring quality care and optimal recovery with our expert medical team Support .', ' Abdominal Gauze Pad Laparotomy in Melbourne  , Abdominal Gauze Pad Laparotomy in Nepal , Abdominal Gauze Pad Laparotomy in Netherlands , Abdominal Gauze Pad Laparotomy in Oman '),
(4, 'Gauze Combine Dressing Pad', '<p>A gauze combine dressing pad, also known simply as a combine dressing or combine pad, is a versatile and highly absorbent wound dressing commonly used in medical settings. It consists of multiple layers of absorbent material, usually cotton or a blend of cotton and synthetic fibers, enclosed within a non-woven fabric cover.</p> <p>     The combine dressing pad is designed to provide optimal wound management by effectively absorbing blood, exudate, and other fluids while maintaining a moist environment conducive to wound healing. Its multi-layered construction allows for efficient fluid retention without sticking to the wound bed, minimizing trauma and discomfort during dressing changes. </p> <p>     One of the distinctive features of a combine dressing pad is its ability to provide both absorption and protection to the wound. The outer non-woven fabric cover serves as a protective barrier, preventing external contaminants from entering the wound while also helping to maintain a sterile environment. Meanwhile, the inner layers of absorbent material quickly wick away fluids, keeping the wound clean and dry. </p> <p>     Combine dressings are available in various sizes to suit different wound types and can be used for a wide range of injuries, including lacerations, abrasions, and surgical wounds. They are often used in conjunction with a secondary dressing, such as a bandage or adhesive tape, to secure the dressing in place and provide additional protection. </p>  ', 'img/product/4.jpg', 'Gauze-Combine-Dressing-Pad', 'Introducing our Gauze Combine Dressing Pad, a versatile and essential component in wound care management. Meticulously ..', ' Gauze Combine Dressing Pad In Nepal || Globalsurgicare ', 'Find high-quality Gauze Combine Dressing Pad in Nepal, crafted for optimal wound care. These pads are essential in medical kits, offering superior absorption', ' Gauze Combine Dressing Pad In Nepal , Gauze Combine Dressing Pad In Germany , Gauze Combine Dressing Pad In Oman'),
(5, 'Gamjee Roll ( Dressing Roll )', '<p>A Gamjee roll, also known as a dressing roll, is a type of wound dressing commonly used in medical settings for the management of various types of wounds, particularly those with moderate to heavy exudate. It consists of multiple layers of absorbent material, typically cotton or a blend of cotton and viscose, enclosed within a non-woven fabric cover. If you\'re looking for a reliable <a href=\"single-product.php?slug=Gamjee-Roll-Dressing-Roll\"> Gamjee Roll Supplier in UAE</a>, consider options that provide high-quality products meeting medical standards.</p> <p>     The term \"Gamjee\" is derived from the name of the Indian city of Gamjee, where this type of dressing was originally manufactured. Over time, it has become a generic term used to refer to this specific type of dressing roll. </p> <p>     Gamjee rolls are designed to provide optimal wound care by effectively absorbing excess exudate while maintaining a moist environment conducive to wound healing. The multiple layers of absorbent material within the dressing roll allow for efficient fluid retention, preventing the wound from becoming too wet or macerated. </p> <p>     One of the key benefits of Gamjee rolls is their versatility and adaptability to different wound sizes and shapes. They can be easily cut to size or folded to fit the contours of the wound bed, providing full coverage and protection. Additionally, their soft and conformable nature ensures patient comfort during wear. </p>  ', 'img/product/5.jpg', 'Gamjee-Roll-Dressing-Roll ', 'ntroducing our Gamjee Roll, a versatile and indispensable dressing roll for wound care management. Expertly... ', ' Gamjee Roll Supplier  in UAE || Best Globalsurgicare', 'Gamjee Roll Supplier  in UAE Contains absorbent cotton, wrapped cotton gauze bundle to use in the hospital to operate patient better and bandage him carefully.', 'Gamjee Roll Supplier  in UAE , Gamjee Roll exporters in Nairobi , Gamjee Roll Supplier  in South Africa  '),
(6, 'Dressing Kit', '<p>A dressing kit, also known as a wound care kit or dressing change kit, is a collection of sterile medical supplies and instruments used for the management and dressing of wounds. These kits are essential tools in healthcare settings, including hospitals, clinics, and home care settings, where they are used to perform wound care procedures safely and effectively.\n\nThe contents of a dressing kit can vary depending on the specific needs of the patient and the type of wound being treated. However, some common items typically found in a dressing kit include:\n\nSterile gloves: Used to maintain aseptic technique and prevent contamination of the wound during dressing changes.\nSterile gauze pads or swabs: Used for cleaning the wound and absorbing excess exudate.\nAdhesive or non-adhesive wound dressings: Used to cover and protect the wound, promote healing, and maintain a moist environment.\nAdhesive tape or bandages: Used to secure the dressing in place and provide additional protection.\nAntiseptic solution or wipes: Used for wound cleansing and disinfection to prevent infection.\nAs a <a href=\"single-product.php?slug=Dressing-Kit\"> Dressing Kit Supplier In France</a>, ensuring the availability of these essential components is crucial for facilitating effective wound care management across various healthcare facilities.</p>', 'img/product/6.jpg', 'Dressing-Kit', 'ntroducing our comprehensive Dressing Kit, a complete solution for wound care needs in medical settings...', 'Dressing Kit Supplier In France || Globalsurgicare', 'Reliable dressing kit supplier in France, offering high-quality medical supplies to meet your healthcare needs with prompt delivery and exceptional service', ' Dressing Kit Supplier In Oman  , Dressing Kit Supplier In India , Dressing Kit Supplier In France , Dressing Kit Supplier In Australia'),
(7, 'Dialysis ONOFF kit', '<p>A dialysis ON/OFF kit, also known as a dialysis access kit or hemodialysis kit, is a specialized set of medical supplies used in hemodialysis procedures to establish and maintain access to the patient\'s bloodstream during dialysis treatment. <a href=\"single-product.php?slug=Dialysis-ONOFF-kit\"> Dialysis ON/OFF kit Supplier in France </a> are essential for ensuring the seamless operation of hemodialysis, a life-saving procedure used to remove waste products and excess fluids from the blood when the kidneys are unable to perform this function adequately.</p> <p>     The dialysis ON/OFF kit typically contains a variety of sterile supplies and equipment necessary for vascular access, monitoring, and connection to the dialysis machine. While the specific contents of the kit may vary depending on the healthcare facility\'s protocols and the patient\'s individual needs, some common items found in a dialysis ON/OFF kit include: </p> <ul class=\" \">     <li>Dialysis catheters: These are flexible tubes inserted into a large vein, usually in the neck (temporary catheter) or chest (tunneled catheter), to allow blood to flow to and from the dialysis machine.</li>     <li>Antiseptic solution or wipes: Used to clean the skin around the catheter insertion site to prevent infection.</li>     <li>Sterile gloves: Worn by healthcare providers to maintain aseptic technique during catheter insertion and care.</li>     <li>Adhesive tape or bandages: Used to secure the dressing in place and provide additional protection.</li>     <li>Dressing materials: Sterile gauze pads, transparent dressings, or specialized securement devices used to cover and protect the catheter site and maintain sterility.</li> </ul>  ', 'img/product/7.jpg', 'Dialysis-ONOFF-kit', ' ChatGPT A dialysis ON/OFF kit, also known as a dialysis access kit or hemodialysis kit, is a specialized set of medical supplies used in hemodialysis procedures to establish ', 'Dialysis ON/OFF kit Supplier in France || Globalsurgicare', 'Dialysis ON/OFF kit supplier in France Contact us for high-quality dialysis solutions, tailored for your needs. Fast delivery and top-notch service! book now', 'dialysis ON/OFF kit Supplier in France  , dialysis ON/OFF kit Supplier in Australia , dialysis ON/OFF kit Supplier in UAE'),
(8, 'Absorbent Gauze', '<p>\nAbsorbent gauze is a type of medical dressing made from loosely woven cotton fibers or a blend of cotton and synthetic materials. It is designed to absorb fluids such as blood, exudate, and other bodily fluids from wounds or surgical sites, helping to keep the area clean and dry for optimal healing.\n</p>\n<p>In addition to wound care, absorbent gauze may also be used for other purposes such as applying topical medications or cleaning medical instruments. It is an essential component of any medical first aid kit and is commonly used in hospitals, clinics, and other healthcare settings.</p>', 'img/product/8.jpg', 'Absorbent-Gauze', 'Absorbent gauze is a type of medical dressing made from loosely woven cotton fibers or...', 'Gauze Combine Dressing Pad In Nepal || Globalsurgicare ', 'Find high-quality Gauze Combine Dressing Pad in Nepal, crafted for optimal wound care. These pads are essential in medical kits, offering superior absorption', 'Gauze Combine Dressing Pad In Nepal , Gauze Combine Dressing Pad In Germany , Gauze Combine Dressing Pad In Oman'),
(9, 'Roller gauze bandages', '<p>\nRoller gauze bandages, also known as roller bandages or rolled gauze, are versatile and commonly used medical dressings for securing wound dressings, providing support, and immobilizing injured limbs. They consist of a long strip of woven cotton gauze that is rolled into a compact cylinder or spool for easy storage and dispensing.\n\nAs a <a href=\"single-product.php?slug=Roller-Gauze-bandage\"> Roller Gauze Bandage Supplier In France</a>, ensuring the availability of high-quality roller gauze bandages is essential for healthcare providers across various settings. These bandages are crucial for maintaining wound care protocols and ensuring patient comfort and stability during recovery.</p>', 'img/product/9.jpg', 'Roller-Gauze-bandage', ' \r\nRoller gauze bandages, also known as roller bandages or rolled gauze, are versatile and commonly...', 'Roller Gauze Bandage Supplier In France || Globalsurgicare', 'For top-quality medical supplies, choose the leading Roller Gauze Bandage Supplier in France, offering reliable, sterile, affordable products for your needs', ' Roller Gauze Bandage Supplier In France  , Roller Gauze Bandage Supplier In Kenya , Roller Gauze Bandage Supplier In Nepal ,'),
(10, 'Open Weave Bandage', '<p>\nOpen weave bandages, also known as net or mesh bandages, are a type of medical dressing characterized by their breathable and flexible construction. Unlike traditional woven bandages, open weave bandages feature a porous mesh design that allows for increased airflow and ventilation while providing support and protection to wounds or injuries.</p>\n\n<p>\n<p>\nHere are some key features and uses of open weave bandages:\n\nBreathability: The open mesh design of these bandages allows air to circulate freely around the wound, promoting ventilation and helping to maintain a dry and comfortable environment. This breathability is particularly beneficial for wounds that require extended periods of dressing wear or for patients with sensitive or fragile skin.\n\n\n\n</p>', 'img/product/10.jpg', 'Open-Weave-Bandage', 'Open weave bandages, also known as net or mesh bandages, are a type of medical...', 'Open Weave Bandage Exporters in Melbourne | Globalsurgicare', 'Medical supplies, trust the leading Open Weave Bandage Exporters in Melbourne. Quality, reliability, and excellent service for all your healthcare needs.', 'Open Weave Bandage Exporters in Melbourne  , Open Weave Bandage Exporters in Netherlands ,Open Weave Bandage Exporters in Nepal , '),
(11, 'Absorbent Cotton Gauze', '<p>\nAbsorbent cotton gauze, also simply referred to as cotton gauze, is a widely used medical dressing made from 100% cotton fibers. It is known for its softness, absorbency, and versatility in wound care.\n\nAbsorbency: Cotton gauze is highly absorbent, making it suitable for managing wounds with moderate to heavy exudate. It effectively wicks away fluids from the wound site, helping to keep the area clean and dry for optimal healing.\n\nAs an <a href=\"single-product.php?slug=Absorbent-Cotton-Gauze\"> Absorbent Cotton Gauze Supplier In UAE </a>, ensuring the availability of high-quality cotton gauze is crucial for healthcare providers across the region. Its superior absorbency and soft texture make it an essential component in wound care protocols.</p>', 'img/product/11.jpg', 'Absorbent-Cotton-Gauze', 'Absorbent cotton gauze, also simply referred to as cotton gauze, is a widely used medical dressing...', 'Absorbent Cotton Gauze Supplier In UAE || Globalsurgicare', 'For top-quality medical supplies, trust the leading Absorbent Cotton Gauze Supplier in UAE, offering reliable, sterile, and affordable products for all health', 'Open Weave Bandage Exporters in Melbourne  , Open Weave Bandage Exporters in Netherlands ,Open Weave Bandage Exporters in Nepal ,'),
(12, 'Infusion Set', '<p>An infusion set is a medical device used to deliver fluids, medications, or nutrients directly into a patient\'s bloodstream or subcutaneous tissue. It consists of several components that work together to administer the infusion safely and effectively. Infusion sets are commonly used in healthcare settings, including hospitals, clinics, and home care, for various purposes such as intravenous (IV) therapy, blood transfusions, chemotherapy, and insulin delivery for diabetes management.</p>', 'img/product/12.jpg', 'Infusion-Set', 'An infusion set is a medical device used to deliver fluids, medications,...', ' Infusion Set Supplier in Australia || Globalsurgicare ', 'Find your trusted Infusion Set Supplier in Australia We offer reliable products ensuring healthcare excellence. Contact us for superior medical solutions today ', 'Infusion Set Supplier in Australia , Infusion Set Supplier in Nepal , Infusion Set Supplier in Germany');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pro`
--
ALTER TABLE `pro`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pro`
--
ALTER TABLE `pro`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
